// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/cardano/13169111
//   https://jiti.indexing.co/networks/cardano/13169011
//   https://jiti.indexing.co/networks/cardano/13168111
// Samples: 3
export interface CardanoBlockBlockIdentifier {
  index: number;
  hash: string;
}

export interface CardanoBlockParentBlockIdentifier {
  index: number;
  hash: string;
}

export interface CardanoBlockTransactionsTransactionIdentifier {
  hash: string;
}

export interface CardanoBlockTransactionsOperationsOperationIdentifier {
  index: number;
  network_index?: number;
}

export interface CardanoBlockTransactionsOperationsAccount {
  address: string;
}

export interface CardanoBlockTransactionsOperationsAmountCurrency {
  symbol: string;
  decimals: number;
}

export interface CardanoBlockTransactionsOperationsAmount {
  value: string;
  currency: CardanoBlockTransactionsOperationsAmountCurrency;
}

export interface CardanoBlockTransactionsOperationsCoinChangeCoinIdentifier {
  identifier: string;
}

export interface CardanoBlockTransactionsOperationsCoinChange {
  coin_identifier: CardanoBlockTransactionsOperationsCoinChangeCoinIdentifier;
  coin_action: string;
}

export interface CardanoBlockTransactionsOperationsMetadataTokenbundleTokensCurrency {
  symbol: string;
  decimals: number;
}

export interface CardanoBlockTransactionsOperationsMetadataTokenbundleTokens {
  value: string;
  currency: CardanoBlockTransactionsOperationsMetadataTokenbundleTokensCurrency;
}

export interface CardanoBlockTransactionsOperationsMetadataTokenbundle {
  policyId: string;
  tokens: CardanoBlockTransactionsOperationsMetadataTokenbundleTokens[];
}

export interface CardanoBlockTransactionsOperationsMetadataWithdrawalamountCurrency {
  symbol: string;
  decimals: number;
}

export interface CardanoBlockTransactionsOperationsMetadataWithdrawalamount {
  value: string;
  currency: CardanoBlockTransactionsOperationsMetadataWithdrawalamountCurrency;
}

export interface CardanoBlockTransactionsOperationsMetadata {
  tokenBundle?: CardanoBlockTransactionsOperationsMetadataTokenbundle[];
  withdrawalAmount?: CardanoBlockTransactionsOperationsMetadataWithdrawalamount;
}

export interface CardanoBlockTransactionsOperationsRelatedOperations {
  index: number;
}

export interface CardanoBlockTransactionsOperations {
  operation_identifier: CardanoBlockTransactionsOperationsOperationIdentifier;
  type: string;
  status: string;
  account: CardanoBlockTransactionsOperationsAccount;
  amount: CardanoBlockTransactionsOperationsAmount;
  coin_change: CardanoBlockTransactionsOperationsCoinChange;
  metadata: CardanoBlockTransactionsOperationsMetadata;
  related_operations: CardanoBlockTransactionsOperationsRelatedOperations[];
}

export interface CardanoBlockTransactionsMetadata {
  size: number;
  scriptSize: number;
}

export interface CardanoBlockTransactions {
  transaction_identifier: CardanoBlockTransactionsTransactionIdentifier;
  operations: CardanoBlockTransactionsOperations[];
  metadata: CardanoBlockTransactionsMetadata;
}

export interface CardanoBlockMetadata {
  transactionsCount: number;
  createdBy: string;
  size: number;
  epochNo: number;
  slotNo: number;
}

export interface CardanoBlock {
  block_identifier: CardanoBlockBlockIdentifier;
  parent_block_identifier: CardanoBlockParentBlockIdentifier;
  timestamp: number;
  transactions: CardanoBlockTransactions[];
  metadata: CardanoBlockMetadata;
  _network: string;
  _vm: string;
}
