// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/ethereum/24674633
//   https://jiti.indexing.co/networks/ethereum/24674533
//   https://jiti.indexing.co/networks/ethereum/24673633
//   https://jiti.indexing.co/networks/base/43464980
//   https://jiti.indexing.co/networks/base/43464880
//   https://jiti.indexing.co/networks/base/43463980
//   https://jiti.indexing.co/networks/polygon/84299638
//   https://jiti.indexing.co/networks/polygon/84299538
//   https://jiti.indexing.co/networks/polygon/84298638
//   https://jiti.indexing.co/networks/arbitrum/442610729
//   https://jiti.indexing.co/networks/arbitrum/442610629
//   https://jiti.indexing.co/networks/arbitrum/442609729
// Samples: 12
export interface EvmBlockTransactionsAccesslist {
  address: string;
  storageKeys: string[];
}

export interface EvmBlockTransactionsReceiptLogs {
  address: string;
  topics: string[];
  data: string;
  blockNumber: number;
  transactionHash: string;
  transactionIndex: number;
  blockHash: string;
  blockTimestamp: string;
  logIndex: number;
  removed: boolean;
}

export interface EvmBlockTransactionsReceipt {
  blockHash: string;
  blockNumber: number;
  contractAddress: null | string;
  cumulativeGasUsed: number;
  effectiveGasPrice: number;
  from: string;
  gasUsed: number;
  logs: EvmBlockTransactionsReceiptLogs[];
  logsBloom: string;
  status: boolean;
  to: null | string;
  transactionHash: string;
  transactionIndex: number;
  type: string;
  depositNonce?: string;
  depositReceiptVersion?: string;
  blobGasUsed?: string;
  l1GasPrice?: string;
  l1GasUsed?: string;
  l1Fee?: string;
  l1BaseFeeScalar?: string;
  l1BlobBaseFee?: string;
  l1BlobBaseFeeScalar?: string;
  daFootprintGasScalar?: string;
  gasUsedForL1?: string;
  l1BlockNumber?: string;
  timeboosted?: boolean;
}

/**
 * Value movements applied outside the EVM call tree.
 *
 * Arbitrum Nitro / Orbit chains surface these on the callTracer result as
 * `beforeEVMTransfers` / `afterEVMTransfers`. They carry ArbOS-level gas
 * accounting (`feePayment`, `gasRefund`, `feeCollection`) and — critically —
 * retryable-ticket flows (`escrow`, `prepaid`, `undoRefund`, `refund`) plus
 * `selfDestruct`. A bridge deposit landing via a retryable redemption moves its
 * value in two hops, and only the second appears in the EVM trace tree, so a
 * trace-only reader misses the funding leg entirely.
 *
 * A `null` end means the value was minted or burned against the fee system
 * rather than moved between accounts.
 */
export interface EvmBlockTransactionsOutOfBandTransfer {
  purpose: string;
  from: string | null;
  to: string | null;
  value: string;
}

export interface EvmBlockTransactionsTracesAction {
  from: string;
  callType?: string;
  gas: string;
  input?: string;
  to?: string;
  value: string;
  init?: string;
  creationMethod?: string;
}

export interface EvmBlockTransactionsTraces {
  action: EvmBlockTransactionsTracesAction;
  blockHash: string;
  blockNumber: number;
  result: Record<string, unknown> | null;
  subtraces: number;
  traceAddress: number[];
  transactionHash: string;
  transactionPosition: number;
  type: string;
  error: string;
}

export interface EvmBlockTransactionsAuthorizationlist {
  chainId: string;
  address: string;
  nonce: string;
  yParity: string;
  r: string;
  s: string;
}

export interface EvmBlockTransactions {
  type: number;
  chainId: string;
  nonce: number;
  gas: number;
  maxFeePerGas: string;
  maxPriorityFeePerGas: string;
  to: null | string;
  value: string;
  accessList: EvmBlockTransactionsAccesslist[];
  input: string;
  r: string;
  s: string;
  yParity: string;
  v: string;
  hash: string;
  blockHash: string;
  blockNumber: number;
  transactionIndex: number;
  from: string;
  gasPrice: string;
  receipt: EvmBlockTransactionsReceipt;
  traces: EvmBlockTransactionsTraces[];
  authorizationList: EvmBlockTransactionsAuthorizationlist[];
  sourceHash?: string;
  mint?: string;
  depositReceiptVersion?: string;
  // Arbitrum Nitro / Orbit: value moved outside the EVM call tree (see the interface docs).
  outOfBandTransfers?: EvmBlockTransactionsOutOfBandTransfer[];
}

export interface EvmBlockWithdrawals {
  index: string;
  validatorIndex: string;
  address: string;
  amount: string;
}

export interface EvmBlock {
  hash: string;
  parentHash: string;
  sha3Uncles: string;
  miner: string;
  stateRoot: string;
  transactionsRoot: string;
  receiptsRoot: string;
  logsBloom: string;
  difficulty: string;
  number: number;
  gasLimit: number;
  gasUsed: number;
  timestamp: number;
  extraData: string;
  mixHash: string;
  nonce: string;
  baseFeePerGas: number;
  withdrawalsRoot?: string;
  blobGasUsed?: string;
  excessBlobGas?: string;
  parentBeaconBlockRoot?: string;
  requestsHash?: string;
  size: number;
  uncles: unknown[];
  transactions: EvmBlockTransactions[];
  withdrawals?: EvmBlockWithdrawals[];
  _network: string;
  _vm: string;
  l1BlockNumber?: string;
  sendCount?: string;
  sendRoot?: string;
}
