// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/filecoin/5847092
//   https://jiti.indexing.co/networks/filecoin/5846992
//   https://jiti.indexing.co/networks/filecoin/5846092
// Samples: 3
export interface FilecoinBlockCids {
  '/': string;
}

export interface FilecoinBlockBlocksTicket {
  VRFProof: string;
}

export interface FilecoinBlockBlocksElectionproof {
  WinCount: number;
  VRFProof: string;
}

export interface FilecoinBlockBlocksBeaconentries {
  Round: number;
  Data: string;
}

export interface FilecoinBlockBlocksWinpostproof {
  PoStProof: number;
  ProofBytes: string;
}

export interface FilecoinBlockBlocksParents {
  '/': string;
}

export interface FilecoinBlockBlocksParentstateroot {
  '/': string;
}

export interface FilecoinBlockBlocksParentmessagereceipts {
  '/': string;
}

export interface FilecoinBlockBlocksMessages {
  '/': string;
}

export interface FilecoinBlockBlocksBlsaggregate {
  Type: number;
  Data: string;
}

export interface FilecoinBlockBlocksBlocksig {
  Type: number;
  Data: string;
}

export interface FilecoinBlockBlocks {
  Miner: string;
  Ticket: FilecoinBlockBlocksTicket;
  ElectionProof: FilecoinBlockBlocksElectionproof;
  BeaconEntries: FilecoinBlockBlocksBeaconentries[];
  WinPoStProof: FilecoinBlockBlocksWinpostproof[];
  Parents: FilecoinBlockBlocksParents[];
  ParentWeight: string;
  Height: number;
  ParentStateRoot: FilecoinBlockBlocksParentstateroot;
  ParentMessageReceipts: FilecoinBlockBlocksParentmessagereceipts;
  Messages: FilecoinBlockBlocksMessages;
  BLSAggregate: FilecoinBlockBlocksBlsaggregate;
  Timestamp: number;
  BlockSig: FilecoinBlockBlocksBlocksig;
  ForkSignaling: number;
  ParentBaseFee: string;
}

export interface FilecoinBlockMessagesCid {
  '/': string;
}

export interface FilecoinBlockMessagesBlockmessagesBlsmessagesCid {
  '/': string;
}

export interface FilecoinBlockMessagesBlockmessagesBlsmessages {
  Version: number;
  To: string;
  From: string;
  Nonce: number;
  Value: string;
  GasLimit: number;
  GasFeeCap: string;
  GasPremium: string;
  Method: number;
  Params: string;
  CID: FilecoinBlockMessagesBlockmessagesBlsmessagesCid;
}

export interface FilecoinBlockMessagesBlockmessagesSecpkmessagesMessageCid {
  '/': string;
}

export interface FilecoinBlockMessagesBlockmessagesSecpkmessagesMessage {
  Version: number;
  To: string;
  From: string;
  Nonce: number;
  Value: string;
  GasLimit: number;
  GasFeeCap: string;
  GasPremium: string;
  Method: number;
  Params: null | string;
  CID: FilecoinBlockMessagesBlockmessagesSecpkmessagesMessageCid;
}

export interface FilecoinBlockMessagesBlockmessagesSecpkmessagesSignature {
  Type: number;
  Data: string;
}

export interface FilecoinBlockMessagesBlockmessagesSecpkmessagesCid {
  '/': string;
}

export interface FilecoinBlockMessagesBlockmessagesSecpkmessages {
  Message: FilecoinBlockMessagesBlockmessagesSecpkmessagesMessage;
  Signature: FilecoinBlockMessagesBlockmessagesSecpkmessagesSignature;
  CID: FilecoinBlockMessagesBlockmessagesSecpkmessagesCid;
}

export interface FilecoinBlockMessagesBlockmessagesCids {
  '/': string;
}

export interface FilecoinBlockMessagesBlockmessages {
  BlsMessages: FilecoinBlockMessagesBlockmessagesBlsmessages[];
  SecpkMessages: FilecoinBlockMessagesBlockmessagesSecpkmessages[];
  Cids: FilecoinBlockMessagesBlockmessagesCids[];
}

export interface FilecoinBlockMessages {
  cid: FilecoinBlockMessagesCid;
  blockMessages: FilecoinBlockMessagesBlockmessages;
}

export interface FilecoinBlockReceipts {
  ExitCode: number;
  Return: null | string;
  GasUsed: number;
  EventsRoot: Record<string, unknown> | null;
}

export interface FilecoinBlock {
  Cids: FilecoinBlockCids[];
  Blocks: FilecoinBlockBlocks[];
  Height: number;
  messages: FilecoinBlockMessages[];
  receipts: FilecoinBlockReceipts[];
  _network: string;
  _vm: string;
}
