// Hand-written (NOT generated by scripts/generate-block-types.ts): the generator samples
// live `jiti.indexing.co/networks/<network>/<beat>` payloads, and HEDERA_NATIVE has no
// published beats until oscar's `hedera` pacemaker ships. Regenerate from live samples
// once it does.
//
// Shape mirrors what the pacemaker assembles: the mirror node's `/blocks/{n}` record file
// plus every HAPI record inside its consensus-timestamp window, fetched from
// `/transactions?timestamp=gte:{from}&timestamp=lte:{to}`. Field names are kept verbatim
// from the mirror node so the beat stays diffable against the REST API.

/**
 * An unscaled integer amount as it arrives from the mirror node.
 *
 * Amounts are tinyunits, so a token with 8 decimals and a large supply (JAM/Tune.FM, 4.4e18)
 * crosses 2^53 on ordinary transfers — observed roughly hourly on mainnet. `JSON.parse`
 * cannot hold those, so oscar's pacemaker re-reads the response text and hands the
 * oversized ones back as exact decimal strings. `BigInt()` accepts both forms, which is how
 * every amount below is read.
 */
export type HederaAmount = number | string;

export interface HederaTransfer {
  account: string;
  amount: HederaAmount;
  is_approval?: boolean;
}

export interface HederaTokenTransfer {
  token_id: string;
  account: string;
  amount: HederaAmount;
  is_approval?: boolean;
}

export interface HederaNftTransfer {
  token_id: string;
  serial_number: number | string;
  sender_account_id: string | null;
  receiver_account_id: string | null;
  is_approval?: boolean;
}

export interface HederaStakingRewardTransfer {
  account: string;
  amount: HederaAmount;
}

export interface HederaTransaction {
  charged_tx_fee: HederaAmount;
  consensus_timestamp: string;
  entity_id: string | null;
  memo_base64: string | null;
  name: string;
  nft_transfers: HederaNftTransfer[];
  // The consensus node that submitted the transaction. It collects a slice of the fee, so
  // its entry in `transfers` is overhead rather than a transfer — and reading it off the
  // record beats guessing at a reserved account-number range, which grows over time.
  node: string;
  nonce: number;
  parent_consensus_timestamp: string | null;
  result: string;
  scheduled: boolean;
  staking_reward_transfers: HederaStakingRewardTransfer[];
  token_transfers: HederaTokenTransfer[];
  transaction_hash: string;
  transaction_id: string;
  transfers: HederaTransfer[];
}

export interface HederaBlock {
  count: number;
  hash: string;
  name?: string;
  number: number;
  previous_hash?: string;
  timestamp: { from: string; to: string };
  transactions: HederaTransaction[];
}
