// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/ripple/102922872
//   https://jiti.indexing.co/networks/ripple/102922772
//   https://jiti.indexing.co/networks/ripple/102921872
// Samples: 3
export interface RippleLedgerTransactionsMetadataAffectednodesCreatednodeNewfields {
  Account?: string;
  BookDirectory?: string;
  OwnerNode?: string;
  Sequence?: number;
  TakerGets?: Record<string, unknown> | string;
  TakerPays?: Record<string, unknown> | string;
  ExchangeRate?: string;
  RootIndex?: string;
  TakerGetsCurrency?: string;
  TakerGetsIssuer?: string;
  TakerPaysCurrency?: string;
  TakerPaysIssuer?: string;
  Flags?: number;
  Expiration?: number;
  Amount?: string;
  NFTokenID?: string;
  Owner?: string;
  TicketSequence?: number;
  IndexPrevious?: string;
  Destination?: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesCreatednode {
  LedgerEntryType: string;
  LedgerIndex: string;
  NewFields: RippleLedgerTransactionsMetadataAffectednodesCreatednodeNewfields;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsNftokensNftoken {
  NFTokenID: string;
  URI: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsNftokens {
  NFToken: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsNftokensNftoken;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsHighlimit {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsLowlimit {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAsset {
  currency: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAsset2 {
  currency: string;
  issuer: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAuctionslotPrice {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAuctionslot {
  Account: string;
  Expiration: number;
  Price: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAuctionslotPrice;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsLptokenbalance {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsVoteslotsVoteentry {
  Account: string;
  VoteWeight: number;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsVoteslots {
  VoteEntry?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsVoteslotsVoteentry;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfields {
  Account?: string;
  Balance?: Record<string, unknown> | string;
  Flags: number;
  OwnerCount?: number;
  Sequence?: number;
  IndexPrevious?: string;
  Owner?: string;
  RootIndex?: string;
  IndexNext?: string;
  BurnedNFTokens?: number;
  FirstNFTokenSequence?: number;
  MintedNFTokens?: number;
  TicketCount?: number;
  NFTokens?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsNftokens[];
  NextPageMin?: string;
  PreviousPageMin?: string;
  HighLimit?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsHighlimit;
  HighNode?: string;
  LowLimit?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsLowlimit;
  LowNode?: string;
  BookDirectory?: string;
  BookNode?: string;
  Expiration?: number;
  OwnerNode?: string;
  TakerGets?: Record<string, unknown> | string;
  TakerPays?: Record<string, unknown> | string;
  AMMID?: string;
  Domain?: string;
  EmailHash?: string;
  RegularKey?: string;
  MessageKey?: string;
  ExchangeRate?: string;
  TakerGetsCurrency?: string;
  TakerGetsIssuer?: string;
  TakerPaysCurrency?: string;
  TakerPaysIssuer?: string;
  AccountTxnID?: string;
  Asset?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAsset;
  Asset2?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAsset2;
  AuctionSlot?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsAuctionslot;
  LPTokenBalance?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsLptokenbalance;
  VoteSlots?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfieldsVoteslots[];
  NFTokenID?: string;
  NFTokenMinter?: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsNftokensNftoken {
  NFTokenID: string;
  URI: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsNftokens {
  NFToken: RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsNftokensNftoken;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsLptokenbalance {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfields {
  Balance?: Record<string, unknown> | string;
  OwnerCount?: number;
  Sequence?: number;
  BurnedNFTokens?: number;
  TicketCount?: number;
  NFTokens?: RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsNftokens[];
  NextPageMin?: string;
  PreviousPageMin?: string;
  TakerGets?: Record<string, unknown> | string;
  TakerPays?: Record<string, unknown> | string;
  AccountTxnID?: string;
  LPTokenBalance?: RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfieldsLptokenbalance;
  IndexPrevious?: string;
  IndexNext?: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesModifiednode {
  FinalFields?: RippleLedgerTransactionsMetadataAffectednodesModifiednodeFinalfields;
  LedgerEntryType: string;
  LedgerIndex: string;
  PreviousFields?: RippleLedgerTransactionsMetadataAffectednodesModifiednodePreviousfields;
  PreviousTxnID?: string;
  PreviousTxnLgrSeq?: number;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsNftokensNftoken {
  NFTokenID: string;
  URI: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsNftokens {
  NFToken: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsNftokensNftoken;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsBalance {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsHighlimit {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsLowlimit {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfields {
  Account?: string;
  Flags: number;
  OwnerNode?: string;
  PreviousTxnID: string;
  PreviousTxnLgrSeq: number;
  TicketSequence?: number;
  ExchangeRate?: string;
  RootIndex?: string;
  TakerGetsCurrency?: string;
  TakerGetsIssuer?: string;
  TakerPaysCurrency?: string;
  TakerPaysIssuer?: string;
  BookDirectory?: string;
  BookNode?: string;
  Sequence?: number;
  TakerGets?: Record<string, unknown> | string;
  TakerPays?: Record<string, unknown> | string;
  NFTokens?: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsNftokens[];
  NextPageMin?: string;
  PreviousPageMin?: string;
  Expiration?: number;
  Balance?: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsBalance;
  HighLimit?: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsHighlimit;
  HighNode?: string;
  LowLimit?: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfieldsLowlimit;
  LowNode?: string;
  IndexNext?: string;
  IndexPrevious?: string;
  Owner?: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsNftokensNftoken {
  NFTokenID: string;
  URI: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsNftokens {
  NFToken: RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsNftokensNftoken;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsBalance {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfields {
  NFTokens?: RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsNftokens[];
  TakerGets?: Record<string, unknown> | string;
  TakerPays?: Record<string, unknown> | string;
  Balance?: RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfieldsBalance;
  Flags?: number;
}

export interface RippleLedgerTransactionsMetadataAffectednodesDeletednode {
  FinalFields: RippleLedgerTransactionsMetadataAffectednodesDeletednodeFinalfields;
  LedgerEntryType: string;
  LedgerIndex: string;
  PreviousFields?: RippleLedgerTransactionsMetadataAffectednodesDeletednodePreviousfields;
}

export interface RippleLedgerTransactionsMetadataAffectednodes {
  CreatedNode: RippleLedgerTransactionsMetadataAffectednodesCreatednode;
  ModifiedNode: RippleLedgerTransactionsMetadataAffectednodesModifiednode;
  DeletedNode: RippleLedgerTransactionsMetadataAffectednodesDeletednode;
}

export interface RippleLedgerTransactionsMetadata {
  AffectedNodes: RippleLedgerTransactionsMetadataAffectednodes[];
  TransactionIndex: number;
  TransactionResult: string;
  delivered_amount?: Record<string, unknown> | string;
  DeliveredAmount?: Record<string, unknown> | string;
}

export interface RippleLedgerTransactionsMemosMemo {
  MemoData: string;
  MemoType?: string;
  MemoFormat?: string;
}

export interface RippleLedgerTransactionsMemos {
  Memo: RippleLedgerTransactionsMemosMemo;
}

export interface RippleLedgerTransactionsPaths {
  account: string;
  type: number;
  currency: string;
  issuer: string;
}

export interface RippleLedgerTransactionsLimitamount {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactionsSignersSigner {
  Account: string;
  SigningPubKey: string;
  TxnSignature: string;
}

export interface RippleLedgerTransactionsSigners {
  Signer?: RippleLedgerTransactionsSignersSigner;
}

export interface RippleLedgerTransactionsAsset {
  currency: string;
}

export interface RippleLedgerTransactionsAsset2 {
  currency: string;
  issuer: string;
}

export interface RippleLedgerTransactionsLptokenin {
  currency: string;
  issuer: string;
  value: string;
}

export interface RippleLedgerTransactions {
  Account: string;
  Fee: string;
  Flags: number;
  LastLedgerSequence: number;
  Sequence: number;
  SigningPubKey: string;
  TakerGets: Record<string, unknown> | string;
  TakerPays: Record<string, unknown> | string;
  TransactionType: string;
  TxnSignature: string;
  hash: string;
  metaData: RippleLedgerTransactionsMetadata;
  Amount: Record<string, unknown> | string;
  Destination: string;
  DestinationTag: number;
  DeliverMax: Record<string, unknown> | string;
  NFTokenID: string;
  TicketSequence: number;
  SourceTag: number;
  OfferSequence: number;
  DeliverMin: Record<string, unknown> | string;
  SendMax: Record<string, unknown> | string;
  TicketCount: number;
  Memos: RippleLedgerTransactionsMemos[];
  Expiration: number;
  InvoiceID?: string;
  Paths: RippleLedgerTransactionsPaths[][];
  LimitAmount: RippleLedgerTransactionsLimitamount;
  Signers?: RippleLedgerTransactionsSigners[];
  Asset?: RippleLedgerTransactionsAsset;
  Asset2?: RippleLedgerTransactionsAsset2;
  LPTokenIn?: RippleLedgerTransactionsLptokenin;
  Owner?: string;
}

export interface RippleLedgerDiff {
  object_id: string;
  object: Record<string, unknown> | string;
}

export interface RippleLedger {
  account_hash: string;
  close_flags: number;
  close_time: number;
  close_time_human: string;
  close_time_resolution: number;
  close_time_iso: string;
  ledger_hash: string;
  parent_close_time: number;
  parent_hash: string;
  total_coins: string;
  transaction_hash: string;
  ledger_index: string;
  closed: boolean;
  transactions: RippleLedgerTransactions[];
  diff: RippleLedgerDiff[];
  _network: string;
  _vm: string;
}
