// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/bittensor/7762563
//   https://jiti.indexing.co/networks/bittensor/7762463
//   https://jiti.indexing.co/networks/bittensor/7761563
//   https://jiti.indexing.co/networks/polkadot/13494424
//   https://jiti.indexing.co/networks/polkadot/13494324
//   https://jiti.indexing.co/networks/polkadot/13493424
// Samples: 6
export interface SubstrateBlockHeaderDigest {
  logs: string[];
}

export interface SubstrateBlockHeader {
  parentHash: string;
  number: string;
  stateRoot: string;
  extrinsicsRoot: string;
  digest: SubstrateBlockHeaderDigest;
}

export interface SubstrateBlockExtrinsics {
  index: number;
  hash: string;
  signer: string;
  nonce: string;
  method: string;
  args: (Record<string, unknown> | boolean | string | unknown[])[];
}

export interface SubstrateBlock {
  blockNumber: number;
  blockHash: string;
  header: SubstrateBlockHeader;
  extrinsics: SubstrateBlockExtrinsics[];
  _network: string;
  _vm: string;
}
