// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/sui/255195515
//   https://jiti.indexing.co/networks/sui/255195415
//   https://jiti.indexing.co/networks/sui/255194515
// Samples: 3
export interface SuiCheckpointTransactionsTransactionDataTransactionConsensusDeterminedVersionAssignments {
  CancelledTransactionsV2: unknown[];
}

export interface SuiCheckpointTransactionsTransactionDataTransactionInputs {
  type: string;
  objectType: string;
  objectId: string;
  initialSharedVersion: string;
  mutable: boolean;
  valueType: string;
  value: boolean | number | string | unknown[];
  version: string;
  digest: string;
}

export interface SuiCheckpointTransactionsTransactionDataTransactionTransactionsMovecall {
  package: string;
  module: string;
  function: string;
  arguments?: (Record<string, unknown> | string)[];
  type_arguments?: string[];
}

export interface SuiCheckpointTransactionsTransactionDataTransactionTransactions {
  MoveCall: SuiCheckpointTransactionsTransactionDataTransactionTransactionsMovecall;
  SplitCoins?: (Record<string, unknown> | unknown[])[];
  MergeCoins?: (Record<string, unknown> | unknown[])[];
  MakeMoveVec?: (null | unknown[])[];
}

export interface SuiCheckpointTransactionsTransactionDataTransaction {
  kind: string;
  epoch?: string;
  round?: string;
  sub_dag_index?: null;
  commit_timestamp_ms?: string;
  consensus_commit_digest?: string;
  consensus_determined_version_assignments?: SuiCheckpointTransactionsTransactionDataTransactionConsensusDeterminedVersionAssignments;
  additional_state_digest?: string;
  inputs?: SuiCheckpointTransactionsTransactionDataTransactionInputs[];
  transactions?: SuiCheckpointTransactionsTransactionDataTransactionTransactions[];
  randomness_round?: string;
  random_bytes?: number[];
}

export interface SuiCheckpointTransactionsTransactionDataGasdataPayment {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsTransactionDataGasdata {
  payment: SuiCheckpointTransactionsTransactionDataGasdataPayment[];
  owner: string;
  price: string;
  budget: string;
}

export interface SuiCheckpointTransactionsTransactionData {
  messageVersion: string;
  transaction: SuiCheckpointTransactionsTransactionDataTransaction;
  sender: string;
  gasData: SuiCheckpointTransactionsTransactionDataGasdata;
}

export interface SuiCheckpointTransactionsTransaction {
  data: SuiCheckpointTransactionsTransactionData;
  txSignatures: string[];
}

export interface SuiCheckpointTransactionsEffectsStatus {
  status: string;
  error?: string;
}

export interface SuiCheckpointTransactionsEffectsGasused {
  computationCost: string;
  storageCost: string;
  storageRebate: string;
  nonRefundableStorageFee: string;
}

export interface SuiCheckpointTransactionsEffectsModifiedatversions {
  objectId: string;
  sequenceNumber: string;
}

export interface SuiCheckpointTransactionsEffectsSharedobjects {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsEffectsMutatedOwnerShared {
  initial_shared_version: number;
}

export interface SuiCheckpointTransactionsEffectsMutatedOwner {
  Shared?: SuiCheckpointTransactionsEffectsMutatedOwnerShared;
  AddressOwner?: string;
  ObjectOwner?: string;
}

export interface SuiCheckpointTransactionsEffectsMutatedReference {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsEffectsMutated {
  owner: SuiCheckpointTransactionsEffectsMutatedOwner;
  reference: SuiCheckpointTransactionsEffectsMutatedReference;
}

export interface SuiCheckpointTransactionsEffectsGasobjectOwner {
  AddressOwner: string;
}

export interface SuiCheckpointTransactionsEffectsGasobjectReference {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsEffectsGasobject {
  owner: SuiCheckpointTransactionsEffectsGasobjectOwner;
  reference: SuiCheckpointTransactionsEffectsGasobjectReference;
}

export interface SuiCheckpointTransactionsEffectsCreatedOwner {
  AddressOwner: string;
}

export interface SuiCheckpointTransactionsEffectsCreatedReference {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsEffectsCreated {
  owner: SuiCheckpointTransactionsEffectsCreatedOwner;
  reference: SuiCheckpointTransactionsEffectsCreatedReference;
}

export interface SuiCheckpointTransactionsEffectsDeleted {
  objectId: string;
  version: number;
  digest: string;
}

export interface SuiCheckpointTransactionsEffectsAborterror {
  module_id: string;
  function: string;
  error_code: number;
}

export interface SuiCheckpointTransactionsEffects {
  messageVersion: string;
  status: SuiCheckpointTransactionsEffectsStatus;
  executedEpoch: string;
  gasUsed: SuiCheckpointTransactionsEffectsGasused;
  modifiedAtVersions: SuiCheckpointTransactionsEffectsModifiedatversions[];
  sharedObjects?: SuiCheckpointTransactionsEffectsSharedobjects[];
  transactionDigest: string;
  mutated: SuiCheckpointTransactionsEffectsMutated[];
  gasObject: SuiCheckpointTransactionsEffectsGasobject;
  dependencies: string[];
  eventsDigest?: string;
  created?: SuiCheckpointTransactionsEffectsCreated[];
  deleted?: SuiCheckpointTransactionsEffectsDeleted[];
  abortError?: SuiCheckpointTransactionsEffectsAborterror;
}

export interface SuiCheckpointTransactionsEventsId {
  txDigest: string;
  eventSeq: string;
}

export interface SuiCheckpointTransactionsEventsParsedjsonOrderDeepPrice {
  asset_is_base: boolean;
  deep_per_asset: string;
}

export interface SuiCheckpointTransactionsEventsParsedjsonCurrentTick {
  bits: number;
}

export interface SuiCheckpointTransactionsEventsParsedjsonTickCurrentIndex {
  bits: number;
}

export interface SuiCheckpointTransactionsEventsParsedjsonTickPreIndex {
  bits: number;
}

export interface SuiCheckpointTransactionsEventsParsedjsonAsset {
  name: string;
}

export interface SuiCheckpointTransactionsEventsParsedjsonA888bd220dbabe932 {
  a300f5009218579d6?: string;
  a44bce80f10717132?: boolean;
  a8108687c4de4ea83?: string;
  ac7f210fc32637b79?: boolean;
  ada1b3c8a2397a876?: boolean;
  aefb8102bf036ff88?: string;
  pool?: string;
}

export interface SuiCheckpointTransactionsEventsParsedjsonA8ea67a9d479b4cc3 {
  a4c9f6a30dfcb26d4: string;
  price: string;
}

export interface SuiCheckpointTransactionsEventsParsedjsonAab80f1dc57a77584 {
  a4c9f6a30dfcb26d4: string;
  price: string;
}

export interface SuiCheckpointTransactionsEventsParsedjson {
  balance_manager_id?: string;
  base_asset_quantity_canceled?: string;
  client_order_id?: string;
  is_bid?: boolean;
  order_id?: string;
  original_quantity?: string;
  pool_id?: string;
  price?: string;
  timestamp?: string;
  trader?: string;
  expire_timestamp?: string;
  placed_quantity?: string;
  cumulative_quote_quantity?: string;
  epoch?: string;
  executed_quantity?: string;
  fee_is_deep?: boolean;
  fill_limit_reached?: boolean;
  fills?: unknown[];
  maker_fees?: string;
  market_order?: boolean;
  order_deep_price?: SuiCheckpointTransactionsEventsParsedjsonOrderDeepPrice;
  order_inserted?: boolean;
  order_type?: number;
  paid_fees?: string;
  self_matching_option?: number;
  status?: number;
  amount?: string;
  beneficiary?: string;
  after_sqrt_price?: string;
  amount_in?: string;
  amount_out?: string;
  atob?: boolean;
  before_sqrt_price?: string;
  fee_amount?: string;
  partner?: string;
  pool?: string;
  ref_amount?: string;
  steps?: string;
  vault_a_amount?: string;
  vault_b_amount?: string;
  partner_id?: string;
  type_name?: string;
  bi?: string;
  bm?: string;
  bo?: string;
  bs?: string;
  si?: string;
  sm?: string;
  so?: string;
  ss?: string;
  EE?: string;
  a2b?: boolean;
  after_liquidity?: string;
  before_liquidity?: string;
  current_tick?: SuiCheckpointTransactionsEventsParsedjsonCurrentTick;
  exceeded?: boolean;
  fee?: string;
  pool_coin_a_amount?: string;
  pool_coin_b_amount?: string;
  sequence_number?: string;
  a27ddd31886860775?: string;
  a4ad9d24a601f5a60?: string[];
  a52aea689b5e0eb4e?: string[];
  a74b4e85f3b283ef9?: string;
  a7995ce3041d46cb2?: string[];
  a7d027a58611a0718?: string;
  a863166978b7b5c02?: number;
  a8c11751b5c54d9f3?: string[];
  a8fabacfbc9a53eab?: string;
  ab857dba7b77c5937?: string;
  ac21553e7b18debdd?: string;
  ac6f0e10915f54802?: string;
  ae5a8c85f7339c42f?: string;
  timestamp_ms?: string;
  gas_price?: string;
  mean?: string;
  variance?: string;
  a_to_b?: boolean;
  amount_a?: string;
  amount_b?: string;
  is_exact_in?: boolean;
  liquidity?: string;
  protocol_fee?: string;
  recipient?: string;
  sqrt_price?: string;
  tick_current_index?: SuiCheckpointTransactionsEventsParsedjsonTickCurrentIndex;
  tick_pre_index?: SuiCheckpointTransactionsEventsParsedjsonTickPreIndex;
  asset?: SuiCheckpointTransactionsEventsParsedjsonAsset;
  deposit?: boolean;
  a1c7efc41c3937d9d?: string;
  a31f11751781e6c71?: string;
  a9df70c4191cc59c8?: string;
  ac7f210fc32637b79?: boolean;
  a888bd220dbabe932?: SuiCheckpointTransactionsEventsParsedjsonA888bd220dbabe932[];
  a8ea67a9d479b4cc3?: SuiCheckpointTransactionsEventsParsedjsonA8ea67a9d479b4cc3[];
  aab80f1dc57a77584?: SuiCheckpointTransactionsEventsParsedjsonAab80f1dc57a77584[];
  sender?: string;
  user_id?: string;
}

export interface SuiCheckpointTransactionsEvents {
  id: SuiCheckpointTransactionsEventsId;
  packageId: string;
  transactionModule: string;
  sender: string;
  type: string;
  parsedJson: SuiCheckpointTransactionsEventsParsedjson;
  bcsEncoding: string;
  bcs: string;
}

export interface SuiCheckpointTransactionsObjectchangesOwnerShared {
  initial_shared_version: number;
}

export interface SuiCheckpointTransactionsObjectchangesOwner {
  Shared?: SuiCheckpointTransactionsObjectchangesOwnerShared;
  AddressOwner?: string;
  ObjectOwner?: string;
}

export interface SuiCheckpointTransactionsObjectchanges {
  type: string;
  sender: string;
  owner: SuiCheckpointTransactionsObjectchangesOwner;
  objectType: string;
  objectId: string;
  version: string;
  previousVersion: string;
  digest: string;
}

export interface SuiCheckpointTransactionsBalancechangesOwner {
  AddressOwner: string;
}

export interface SuiCheckpointTransactionsBalancechanges {
  owner: SuiCheckpointTransactionsBalancechangesOwner;
  coinType: string;
  amount: string;
}

export interface SuiCheckpointTransactions {
  digest: string;
  transaction: SuiCheckpointTransactionsTransaction;
  rawTransaction: string;
  effects: SuiCheckpointTransactionsEffects;
  events: SuiCheckpointTransactionsEvents[];
  objectChanges: SuiCheckpointTransactionsObjectchanges[];
  balanceChanges: SuiCheckpointTransactionsBalancechanges[];
  timestampMs: string;
  checkpoint: string;
  rawEffects: number[];
}

export interface SuiCheckpoint {
  sequence: string;
  digest: string;
  timestamp: string;
  transactions: SuiCheckpointTransactions[];
  _network: string;
  _vm: string;
}
