// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/solana/406934053
//   https://jiti.indexing.co/networks/solana/406933953
//   https://jiti.indexing.co/networks/solana/406933053
//   https://jiti.indexing.co/networks/eclipse/143074735
//   https://jiti.indexing.co/networks/eclipse/143074635
//   https://jiti.indexing.co/networks/eclipse/143073735
// Samples: 6
export interface SvmBlockTransactionsTransactionMessageHeader {
  numRequiredSignatures: number;
  numReadonlySignedAccounts: number;
  numReadonlyUnsignedAccounts: number;
}

export interface SvmBlockTransactionsTransactionMessageInstructions {
  programIdIndex: number;
  accounts: number[];
  data: string;
  stackHeight: null | number;
}

export interface SvmBlockTransactionsTransactionMessageAddresstablelookups {
  accountKey: string;
  writableIndexes: number[];
  readonlyIndexes: number[];
}

export interface SvmBlockTransactionsTransactionMessage {
  header: SvmBlockTransactionsTransactionMessageHeader;
  accountKeys: string[];
  recentBlockhash: string;
  instructions: SvmBlockTransactionsTransactionMessageInstructions[];
  addressTableLookups?: SvmBlockTransactionsTransactionMessageAddresstablelookups[];
}

export interface SvmBlockTransactionsTransaction {
  signatures: string[];
  message: SvmBlockTransactionsTransactionMessage;
}

export interface SvmBlockTransactionsMetaStatusErr {
  InstructionError: (Record<string, unknown> | number | string)[];
}

export interface SvmBlockTransactionsMetaStatus {
  Ok?: null;
  Err?: SvmBlockTransactionsMetaStatusErr;
}

export interface SvmBlockTransactionsMetaInnerinstructionsInstructions {
  programIdIndex: number;
  accounts: number[];
  data: string;
  stackHeight: number;
}

export interface SvmBlockTransactionsMetaInnerinstructions {
  index: number;
  instructions: SvmBlockTransactionsMetaInnerinstructionsInstructions[];
}

export interface SvmBlockTransactionsMetaPretokenbalancesUitokenamount {
  uiAmount: number;
  decimals: number;
  amount: string;
  uiAmountString: string;
}

export interface SvmBlockTransactionsMetaPretokenbalances {
  accountIndex: number;
  mint: string;
  uiTokenAmount: SvmBlockTransactionsMetaPretokenbalancesUitokenamount;
  owner: string;
  programId: string;
}

export interface SvmBlockTransactionsMetaPosttokenbalancesUitokenamount {
  uiAmount: number;
  decimals: number;
  amount: string;
  uiAmountString: string;
}

export interface SvmBlockTransactionsMetaPosttokenbalances {
  accountIndex: number;
  mint: string;
  uiTokenAmount: SvmBlockTransactionsMetaPosttokenbalancesUitokenamount;
  owner: string;
  programId: string;
}

export interface SvmBlockTransactionsMetaLoadedaddresses {
  writable: string[];
  readonly: string[];
}

export interface SvmBlockTransactionsMetaReturndata {
  programId: string;
  data: string[];
}

export interface SvmBlockTransactionsMeta {
  err: Record<string, unknown> | null;
  status: SvmBlockTransactionsMetaStatus;
  fee: number;
  preBalances: number[];
  postBalances: number[];
  innerInstructions: SvmBlockTransactionsMetaInnerinstructions[];
  logMessages: string[];
  preTokenBalances: SvmBlockTransactionsMetaPretokenbalances[];
  postTokenBalances: SvmBlockTransactionsMetaPosttokenbalances[];
  rewards: unknown[];
  loadedAddresses: SvmBlockTransactionsMetaLoadedaddresses;
  computeUnitsConsumed: number;
  costUnits?: number;
  returnData?: SvmBlockTransactionsMetaReturndata;
}

export interface SvmBlockTransactions {
  transaction: SvmBlockTransactionsTransaction;
  meta: SvmBlockTransactionsMeta;
  version: number | string;
}

export interface SvmBlockRewards {
  pubkey: string;
  lamports: number;
  postBalance: number;
  rewardType: string;
  commission: null;
}

export interface SvmBlock {
  previousBlockhash: string;
  blockhash: string;
  parentSlot: number;
  transactions: SvmBlockTransactions[];
  rewards: SvmBlockRewards[];
  blockTime: number;
  blockHeight: number;
  _network: string;
  _vm: string;
}
