// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/ton/58384846
//   https://jiti.indexing.co/networks/ton/58384746
//   https://jiti.indexing.co/networks/ton/58383846
// Samples: 3
export interface TonBlockShardsId {
  '@type': string;
  workchain: number;
  shard: string;
  seqno: number;
  root_hash: string;
  file_hash: string;
}

export interface TonBlockShardsPrevBlocks {
  '@type': string;
  workchain: number;
  shard: string;
  seqno: number;
  root_hash: string;
  file_hash: string;
}

export interface TonBlockShardsTransactionsAddress {
  '@type': string;
  account_address: string;
}

export interface TonBlockShardsTransactionsTransactionId {
  '@type': string;
  lt: string;
  hash: string;
}

export interface TonBlockShardsTransactionsInMsgSource {
  '@type': string;
  account_address: string;
}

export interface TonBlockShardsTransactionsInMsgDestination {
  '@type': string;
  account_address: string;
}

export interface TonBlockShardsTransactionsInMsgMsgData {
  '@type': string;
  body?: string;
  init_state?: string;
  text?: string;
}

export interface TonBlockShardsTransactionsInMsg {
  '@type': string;
  hash: string;
  source: TonBlockShardsTransactionsInMsgSource;
  destination: TonBlockShardsTransactionsInMsgDestination;
  value: string;
  extra_currencies: unknown[];
  fwd_fee: string;
  ihr_fee: string;
  created_lt: string;
  body_hash: string;
  msg_data: TonBlockShardsTransactionsInMsgMsgData;
}

export interface TonBlockShardsTransactionsOutMsgsSource {
  '@type': string;
  account_address: string;
}

export interface TonBlockShardsTransactionsOutMsgsDestination {
  '@type': string;
  account_address: string;
}

export interface TonBlockShardsTransactionsOutMsgsMsgData {
  '@type': string;
  body?: string;
  init_state?: string;
  text?: string;
}

export interface TonBlockShardsTransactionsOutMsgs {
  '@type': string;
  hash: string;
  source: TonBlockShardsTransactionsOutMsgsSource;
  destination: TonBlockShardsTransactionsOutMsgsDestination;
  value: string;
  extra_currencies: unknown[];
  fwd_fee: string;
  ihr_fee: string;
  created_lt: string;
  body_hash: string;
  msg_data: TonBlockShardsTransactionsOutMsgsMsgData;
}

export interface TonBlockShardsTransactions {
  '@type': string;
  address: TonBlockShardsTransactionsAddress;
  utime: number;
  data: string;
  transaction_id: TonBlockShardsTransactionsTransactionId;
  fee: string;
  storage_fee: string;
  other_fee: string;
  in_msg: TonBlockShardsTransactionsInMsg;
  out_msgs: TonBlockShardsTransactionsOutMsgs[];
  account: string;
}

export interface TonBlockShards {
  '@type': string;
  id: TonBlockShardsId;
  global_id: number;
  version: number;
  flags: number;
  after_merge: boolean;
  after_split: boolean;
  before_split: boolean;
  want_merge: boolean;
  want_split: boolean;
  validator_list_hash_short: number;
  catchain_seqno: number;
  min_ref_mc_seqno: number;
  is_key_block: boolean;
  prev_key_block_seqno: number;
  start_lt: string;
  end_lt: string;
  gen_utime: number;
  vert_seqno: number;
  prev_blocks: TonBlockShardsPrevBlocks[];
  '@extra': string;
  transactions: TonBlockShardsTransactions[];
}

export interface TonBlock {
  seqno: number;
  shards: TonBlockShards[];
  _network: string;
  _vm: string;
}
