// Auto-generated by scripts/generate-block-types.ts
// Generated: 2026-03-17
// Sources:
//   https://jiti.indexing.co/networks/bitcoin/940963
//   https://jiti.indexing.co/networks/bitcoin/940863
//   https://jiti.indexing.co/networks/bitcoin/939963
//   https://jiti.indexing.co/networks/dogecoin/6126894
//   https://jiti.indexing.co/networks/dogecoin/6126794
//   https://jiti.indexing.co/networks/dogecoin/6125894
//   https://jiti.indexing.co/networks/zcash/3275181
//   https://jiti.indexing.co/networks/zcash/3275081
//   https://jiti.indexing.co/networks/zcash/3274181
// Samples: 9
export interface UtxoBlockTxVinScriptsig {
  asm: string;
  hex: string;
}

export interface UtxoBlockTxVinPrevoutScriptpubkey {
  asm: string;
  desc: string;
  hex: string;
  address: string;
  type: string;
}

export interface UtxoBlockTxVinPrevout {
  generated: boolean;
  height: number;
  value: number;
  scriptPubKey: UtxoBlockTxVinPrevoutScriptpubkey;
}

export interface UtxoBlockTxVin {
  coinbase: string;
  txinwitness: string[];
  sequence: number;
  txid: string;
  vout: number;
  scriptSig: UtxoBlockTxVinScriptsig;
  prevout: UtxoBlockTxVinPrevout;
}

export interface UtxoBlockTxVoutScriptpubkey {
  asm: string;
  desc?: string;
  hex: string;
  address?: string;
  type: string;
  reqSigs?: number;
  addresses?: string[];
}

export interface UtxoBlockTxVout {
  value: number;
  n: number;
  scriptPubKey: UtxoBlockTxVoutScriptpubkey;
  valueZat: number;
}

export interface UtxoBlockTxVshieldedoutput {
  cv?: string;
  cmu?: string;
  ephemeralKey?: string;
  encCiphertext?: string;
  outCiphertext?: string;
  proof?: string;
}

export interface UtxoBlockTxOrchardActions {
  cv?: string;
  nullifier?: string;
  rk?: string;
  cmx?: string;
  ephemeralKey?: string;
  encCiphertext?: string;
  spendAuthSig?: string;
  outCiphertext?: string;
}

export interface UtxoBlockTxOrchardFlags {
  enableOutputs: boolean;
  enableSpends: boolean;
}

export interface UtxoBlockTxOrchard {
  actions: UtxoBlockTxOrchardActions[];
  valueBalance: number;
  valueBalanceZat: number;
  flags?: UtxoBlockTxOrchardFlags;
  anchor?: string;
  proof?: string;
  bindingSig?: string;
}

export interface UtxoBlockTx {
  txid: string;
  hash: string;
  version: number;
  size: number;
  vsize: number;
  weight: number;
  locktime: number;
  vin: UtxoBlockTxVin[];
  vout: UtxoBlockTxVout[];
  hex: string;
  fee: number;
  blockhash: string;
  confirmations: number;
  time: number;
  blocktime: number;
  in_active_chain: boolean;
  height: number;
  vShieldedSpend: unknown[];
  vShieldedOutput: UtxoBlockTxVshieldedoutput[];
  vjoinsplit: unknown[];
  orchard: UtxoBlockTxOrchard;
  valueBalance: number;
  valueBalanceZat: number;
  authdigest: string;
  overwintered: boolean;
  versiongroupid: string;
  expiryheight: number;
  bindingSig?: string;
}

export interface UtxoBlockAuxpowTxVin {
  coinbase?: string;
  sequence?: number;
}

export interface UtxoBlockAuxpowTxVoutScriptpubkey {
  asm: string;
  hex: string;
  reqSigs?: number;
  type: string;
  addresses?: string[];
}

export interface UtxoBlockAuxpowTxVout {
  value?: number;
  n?: number;
  scriptPubKey?: UtxoBlockAuxpowTxVoutScriptpubkey;
}

export interface UtxoBlockAuxpowTx {
  hex: string;
  txid: string;
  hash: string;
  size: number;
  vsize: number;
  version: number;
  locktime: number;
  vin: UtxoBlockAuxpowTxVin[];
  vout: UtxoBlockAuxpowTxVout[];
  blockhash: string;
}

export interface UtxoBlockAuxpow {
  tx: UtxoBlockAuxpowTx;
  index: number;
  chainindex: number;
  merklebranch: string[];
  chainmerklebranch: string[];
  parentblock: string;
}

export interface UtxoBlockChainsupply {
  chainValue: number;
  chainValueZat: number;
  monitored: boolean;
}

export interface UtxoBlockValuepools {
  id: string;
  chainValue: number;
  chainValueZat: number;
  monitored: boolean;
  valueDelta: number;
  valueDeltaZat: number;
}

export interface UtxoBlockTreesSapling {
  size: number;
}

export interface UtxoBlockTreesOrchard {
  size: number;
}

export interface UtxoBlockTrees {
  sapling: UtxoBlockTreesSapling;
  orchard: UtxoBlockTreesOrchard;
}

export interface UtxoBlock {
  hash: string;
  confirmations: number;
  height: number;
  version: number;
  versionHex?: string;
  merkleroot: string;
  time: number;
  mediantime?: number;
  nonce: number | string;
  bits: string;
  target?: string;
  difficulty: number;
  chainwork?: string;
  nTx?: number;
  previousblockhash: string;
  strippedsize?: number;
  size: number;
  weight?: number;
  tx: UtxoBlockTx[];
  _network: string;
  _vm: string;
  nextblockhash?: string;
  auxpow?: UtxoBlockAuxpow;
  blockcommitments?: string;
  finalsaplingroot?: string;
  finalorchardroot?: string;
  solution?: string;
  chainSupply?: UtxoBlockChainsupply;
  valuePools?: UtxoBlockValuepools[];
  trees?: UtxoBlockTrees;
}
