name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - run: npm install
      
      - name: Bump Version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npm version patch --no-git-tag-version
      
      - run: npm run build
      
      - name: Commit and Push Changes
        run: |
          git add package.json package-lock.json
          git commit -m "Auto-update package version" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/indexing-co/jiti.git HEAD:main || echo "No changes to push"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}